"""empty message

Revision ID: 11687ee0363f
Revises: 8abb62878858
Create Date: 2021-12-01 18:41:40.271079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11687ee0363f'
down_revision = '8abb62878858'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_time', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('report_time')

    # ### end Alembic commands ###
