"""empty message

Revision ID: 35f05a928cde
Revises: 5402073f638f
Create Date: 2021-11-30 14:19:13.907504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35f05a928cde'
down_revision = '5402073f638f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('college_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('certification', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_users_student_id')
        batch_op.create_index(batch_op.f('ix_users_certification'), ['certification'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_college_id'), ['college_id'], unique=True)
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.INTEGER(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_users_college_id'))
        batch_op.drop_index(batch_op.f('ix_users_certification'))
        batch_op.create_index('ix_users_student_id', ['student_id'], unique=False)
        batch_op.drop_column('certification')
        batch_op.drop_column('college_id')

    # ### end Alembic commands ###
