"""empty message

Revision ID: 8abb62878858
Revises: ca63dfa9c9ef
Create Date: 2021-12-01 18:05:49.994646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8abb62878858'
down_revision = 'ca63dfa9c9ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ranks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('website', sa.String(length=256), nullable=True),
    sa.Column('picture_path', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ranks')),
    sa.UniqueConstraint('website', name=op.f('uq_ranks_website'))
    )
    with op.batch_alter_table('ranks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ranks_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_ranks_name'), ['name'], unique=True)

    with op.batch_alter_table('certifications', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_certifications_teacher_id_users'), 'users', ['teacher_id'], ['college_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certifications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_certifications_teacher_id_users'), type_='foreignkey')

    with op.batch_alter_table('ranks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ranks_name'))
        batch_op.drop_index(batch_op.f('ix_ranks_country'))

    op.drop_table('ranks')
    # ### end Alembic commands ###
