"""empty message

Revision ID: 94040008b253
Revises: 72c842425e6c
Create Date: 2021-11-30 01:54:56.672545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94040008b253'
down_revision = '72c842425e6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('filename', sa.String(length=64), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('recruitment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recruitment_id'], ['recruitments.id'], name=op.f('fk_resumes_recruitment_id_recruitments')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_resumes_student_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resumes'))
    )
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resumes_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index('ix_applications_timestamp')

    op.drop_table('applications')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('body', sa.TEXT(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=True),
    sa.Column('recruitment_id', sa.INTEGER(), nullable=True),
    sa.Column('filename', sa.VARCHAR(length=64), nullable=False),
    sa.ForeignKeyConstraint(['recruitment_id'], ['recruitments.id'], name='fk_applications_recruitment_id_recruitments'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name='fk_applications_student_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_applications')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index('ix_applications_timestamp', ['timestamp'], unique=False)

    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resumes_timestamp'))

    op.drop_table('resumes')
    # ### end Alembic commands ###
