"""empty message

Revision ID: ca63dfa9c9ef
Revises: 35f05a928cde
Create Date: 2021-12-01 10:35:43.081016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca63dfa9c9ef'
down_revision = '35f05a928cde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('favoriter_id', sa.Integer(), nullable=False),
    sa.Column('favorite_post_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['favorite_post_id'], ['posts.id'], name=op.f('fk_favorites_favorite_post_id_posts')),
    sa.ForeignKeyConstraint(['favoriter_id'], ['users.id'], name=op.f('fk_favorites_favoriter_id_users')),
    sa.PrimaryKeyConstraint('favoriter_id', 'favorite_post_id', name=op.f('pk_favorites'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###
